#pragma once

const char* const patchNames[] = {
    "Brass Set 1",
    "Brass Swell",
    "Trumpet",
    "Flutes",
    "Moving Strings",
    "Brass & Strings",
    "Choir",
    "Piano I",
    "Organ I",
    "Organ II",
    "Combo Organ",
    "Calliope",
    "Donald Pluck",
    "Celeste* (1 oct.up)",
    "Elect. Piano I",
    "Elect. Piano II",
    "Clock Chimes* (1 oct. up)",
    "Steel Drums",
    "Xylophone",
    "Brass III",
    "Fanfare",
    "String III",
    "Pizzicato",
    "High Strings",
    "Bass clarinet",
    "English Horn",
    "Brass Ensemble",
    "Guitar",
    "Koto",
    "Dark Pluck",
    "Funky I",
    "Synth Bass I (unison)",
    "Lead I",
    "Lead II",
    "Lead III",
    "Funky II",
    "Synth Bass II",
    "Funky III",
    "Thud Wah",
    "Going Up",
    "Piano II",
    "Clav",
    "Frontier Organ",
    "Snare Drum (unison)",
    "Tom Toms (unison)",
    "Timpani (unison)",
    "Shaker",
    "Synth Pad",
    "Sweep I",
    "Pluck Sweep",
    "Repeater",
    "Sweep II",
    "Pluck Bell",
    "Dark Synth Piano",
    "Sustainer",
    "Wah Release",
    "Gong (play low chords)",
    "Resonance Funk",
    "Drum Booms* (1 oct. down)",
    "Dust Storm",
    "Rocket Men",
    "Hand Claps",
    "FX Sweep",
    "Caverns",
    "Strings",
    "Violin",
    "Chorus Vibes",
    "Organ 1",
    "Harpsichord 1",
    "Recorder",
    "Perc. Pluck",
    "Noise Sweep",
    "Space Chimes",
    "Nylon Guitar",
    "Orchestral Pad",
    "Bright Pluck",
    "Organ Bell",
    "Accordion",
    "FX Rise 1",
    "FX Rise 2",
    "Brass",
    "Helicopter",
    "Lute",
    "Chorus Funk",
    "Tomita",
    "FX Sweep 1",
    "Sharp Reed",
    "Bass Pluck",
    "Resonant Rise",
    "Harpsichord 2",
    "Dark Ensemble",
    "Contact Wah",
    "Noise Sweep 2",
    "Glassy Wah",
    "Phase Ensemble",
    "Chorused Bell",
    "Clav",
    "Organ 2",
    "Bassoon",
    "Auto Release Noise Sweep",
    "Brass Ensemble",
    "Ethereal",
    "Chorus Bell 2",
    "Blizzard",
    "E. Piano with Tremolo",
    "Clarinet",
    "Thunder",
    "Reedy Organ",
    "Flute / Horn",
    "Toy Rhodes",
    "Surf's Up",
    "OW Bass",
    "Piccolo",
    "Melodic Taps",
    "Meow Brass",
    "Violin (high)",
    "High Bells",
    "Rolling Wah",
    "Ping Bell",
    "Brassy Organ",
    "Low Dark Strings",
    "Piccolo Trumpet",
    "Cello",
    "High Strings",
    "Rocket Men",
    "Forbidden Planet",
    "Froggy",
    "Owgan",
    "BRASS   1",
    "BRASS   2",
    "BRASS   3",
    "STRINGS 1",
    "STRINGS 2",
    "STRINGS 3",
    "ORCHESTRA",
    "PIANO   1",
    "PIANO   2",
    "PIANO   3",
    "E.PIANO 1",
    "GUITAR  1",
    "GUITAR  2",
    "SYN-LEAD 1",
    "BASS    1",
    "BASS    2",
    "E.ORGAN 1",
    "PIPES   1",
    "HARPSICH 1",
    "CLAV    1",
    "VIBE    1",
    "MARIMBA",
    "KOTO",
    "FLUTE   1",
    "ORCH-CHIME",
    "TUB BELLS",
    "STEEL DRUM",
    "TIMPANI",
    "REFS WHISL",
    "VOICE   1",
    "TRAIN",
    "TAKE OFF",
    "PIANO   4",
    "PIANO   5",
    "E.PIANO 2",
    "E.PIANO 3",
    "E.PIANO 4",
    "PIANO 5THS",
    "CELESTE",
    "TOY PIANO",
    "HARPSICH 2",
    "HARPSICH 3",
    "CLAV    2",
    "CLAV    3",
    "E.ORGAN 2",
    "E.ORGAN 3",
    "E.ORGAN 4",
    "E.ORGAN 5",
    "PIPES   2",
    "PIPES   3",
    "PIPES   4",
    "CALIOPE",
    "ACCORDION",
    "SITAR",
    "GUITAR  3",
    "GUITAR  4",
    "GUITAR  5",
    "GUITAR  6",
    "LUTE",
    "BANJO",
    "HARP    1",
    "HARP    2",
    "BASS    3",
    "BASS    4",
    "PICCOLO",
    "FLUTE   2",
    "OBOE",
    "CLARINET",
    "SAX BC",
    "BASSOON",
    "STRINGS 4",
    "STRINGS 5",
    "STRINGS 6",
    "STRINGS 7",
    "STRINGS 8",
    "BRASS   4",
    "BRASS   5",
    "BRASS 6 BC",
    "BRASS   7",
    "BRASS   8",
    "RECORDER",
    "HARMONICA1",
    "HRMNCA2 BC",
    "VOICE   2",
    "VOICE   3",
    "GLOKENSPL",
    "VIBE    2",
    "XYLOPHONE",
    "CHIMES",
    "GONG    1",
    "GONG    2",
    "BELLS",
    "COW BELL",
    "BLOCK",
    "FLEXATONE",
    "LOG DRUM",
    "SYN-LEAD 2",
    "SYN-LEAD 3",
    "SYN-LEAD 4",
    "SYN-LEAD 5",
    "SYN-CLAV 1",
    "SYN-CLAV 2",
    "SYN-CLAV 3",
    "SYN-PIANO",
    "SYNBRASS 1",
    "SYNBRASS 2",
    "SYNORGAN 1",
    "SYNORGAN 2",
    "SYN-VOX",
    "SYN-ORCH",
    "SYN-BASS 1",
    "SYN-BASS 2",
    "HARP-FLUTE",
    "BELL-FLUTE",
    "E.P-BRS BC",
    "T.BL-EXPA",
    "CHIME-STRG",
    "B.DRM-SNAR",
    "SHIMMER",
    "EVOLUTION",
    "WATER GDN",
    "WASP STING",
    "LASER GUN",
    "DESCENT",
    "OCTAVE WAR",
    "GRAND PRIX",
    "ST.HELENS",
    "EXPLOSION",
    "dpwe piano",
    "amyboard default",
};


inline const char* getPatchName(uint16_t patch)
{
    constexpr uint16_t count =
        sizeof(patchNames) /
        sizeof(patchNames[0]);

    if(patch >= count)
        return "";

    return patchNames[patch];
}
